server:
  port: 8182
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.36.100:3306/cloudstudy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyDifficultPass4@
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置mybatis-plus信息
mybatis-plus:
  #  global-config:
  #    db-config:
  #       id生成策略 auto为数据库自增
  #     id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml